blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Neverdecel/OSorganicAI/tree/main/docs
    about: Read the comprehensive documentation
  - name: Template Usage Guide
    url: https://github.com/Neverdecel/OSorganicAI/blob/main/docs/template-usage.md
    about: Learn how to spawn and customize child instances
